project:
  type: website

website:
  title: "Mini Project: Flight Delays"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Mini_Project.qmd
        text: Report

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true